### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by SVijayB** [SVijayB/JavaSpace#1]
## Hacktoberfest 2020

Anyone willing to add a few java programs to the list of already existing programs can do so. 

Make sure you read the [contributing.md](https://github.com/SVijayB/JavaSpace/blob/master/.github/CONTRIBUTING.md) file.

Also, once you add all the programs, make sure you update the readme.md file accordingly. If the program belongs to none of the already existing categories, add it to the miscellaneous section. 

**Happy hacking!**

**Comment by varunvjha** [comment]
Can I work on this issue too?

**Comment by SVijayB** [comment]
Yes, you can.

**Comment by arnoob16** [comment]
@SVijayB Do we need to push a well commented code or we can push our code directly?

**Comment by SVijayB** [comment]
@arnoob16 you can push your code directly.

**Comment by srushtips** [comment]
Hi, can I work on this?

**Comment by SVijayB** [comment]
@srushtips yes, you can.

**Comment by Nunia** [comment]
Hey @SVijayB can i work on this?

**Comment by SVijayB** [comment]
@Nunia yeah, feel free to.
